### ISSUE TITLE
Build Open Canvas

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#24]
Open Canvas for Privacy Board Game.

**Comment by barrosgeraldo** [comment]
# Roadmap
We're working with educators, designers and marketers to build the a board game to everyone that's use the web can learn how to navigate safely using good online security and privacy practices.

Privacy Board Game — Explore and analyze everyday situations on the Internet and learn how to navigate safely using good online security and privacy practices. This game is proudly part of [Offline Games Challenge](https://github.com/MozillaFoundation/mpa-offline-games-challenge) from Mozilla Foundation.

## What do we need to do?

This issue is our roadmap. It's a place to start to investigate the myriad of issues that you can contribute to. Check out the different [milestones](https://github.com/itidigitalbr/privacy-board-game/milestones) listed below, but feel free to explore the [issues by label](https://github.com/itidigitalbr/privacy-board-game/labels) too.

Please check out our [code of conduct](https://github.com/itidigitalbr/privacy-board-game/blob/master/CODE_OF_CONDUCT.md) to help you get started, and the [README](https://github.com/itidigitalbr/privacy-board-game/blob/master/README.md) for an overview if you haven't read it yet!

### Milestone: [Mozilla Festival 2017](https://github.com/itidigitalbr/privacy-board-game/milestone/2)
> After developing our first prototype we will demonstrate our game in a fun session of the Mozilla Festival.
- #37 
- #38 

### Milestone: [Website development](https://github.com/itidigitalbr/privacy-board-game/milestone/4)
>  We will create a simple website to bring all our resources together in an good interface for potential players or facilitators. This will be the key to help us on social media campaigns.
- #19 
- #20 
- #21 
- #22 
- #23 

### Milestone: [Design board game](https://github.com/itidigitalbr/privacy-board-game/milestone/1)
>  The key to our mission here is to develop the game, this milestone ensure that all the tasks are well grouped and easy to track.
- #27 
- #28 
- #29 

### Milestone: [Social media campaign](https://github.com/itidigitalbr/privacy-board-game/milestone/5)
>  In addition to developing our game and creating awesome resources to keep learning moving forward, we need to inform, spread, speak and promote our game. This social media campaign will ensure this.
- #31 
- #32 
- #33 

### Milestone: [Teaching kit](https://github.com/itidigitalbr/privacy-board-game/milestone/3)
>  Educators will be the key to ensuring that more people play our game, we'll make sure they have all the resources, tips and lesson plans easy for a session.
- #34 
- #35 
- #36

**Comment by barrosgg** [comment]
Has been made at [Privacy Board Game](https://docs.google.com/presentation/d/1DxLbSnXOLY-AAQu70tfY65od_r6hZ3obwd6VtzlfeQo/edit?usp=sharing).

**Comment by barrosgg** [comment]
closing
